### ISSUE TITLE
json file

### ISSUE THREAD

**Issue by ghost** [RadioStudent/RadioStudent-Android#1]
please would you post the copy of json file?

**Comment by jl2035** [comment]
It was located here: https://radiostudent.si/mobile-json. For some reason that URL is gone and I've just addressed the current RŠ IT team if they can put it back. Hopefully they will. Stay tuned.

**Comment by ghost** [comment]
Okay thanks

**Comment by jl2035** [comment]
Sorry. I don't think it's gonna happen. I personally checked and the view is gone from the website backend and cannot find it. It was a 'View' in Drupal website if that is of any help.

I recommend you to do this part on your own. Create a custom server action that generates a json response and parse that from Java. You can use my code as a reference, but there might be better ways today.. not sure.

**Comment by ghost** [comment]
okay thanks alot
